// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.ia');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Adder commento";
Blockly.Msg.AUTH = "Per favor autorisa iste application pro permitter de salveguardar tu travalio e pro permitter que tu lo divide con alteres.";
Blockly.Msg.CHANGE_VALUE_TITLE = "Cambiar valor:";
Blockly.Msg.CHAT = "Conversa con tu collaborator scribente in iste quadro!";
Blockly.Msg.CLEAN_UP = "Clarar le blocos";
Blockly.Msg.COLLAPSE_ALL = "Plicar blocos";
Blockly.Msg.COLLAPSE_BLOCK = "Plicar bloco";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "color 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "color 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "ration";
Blockly.Msg.COLOUR_BLEND_TITLE = "miscer";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Misce duo colores con un ration specificate (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://ia.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Elige un color del paletta.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "color aleatori";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Eliger un color al hasardo.";
Blockly.Msg.COLOUR_RGB_BLUE = "blau";
Blockly.Msg.COLOUR_RGB_GREEN = "verde";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "rubie";
Blockly.Msg.COLOUR_RGB_TITLE = "colorar con";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Crear un color con le quantitate specificate de rubie, verde e blau. Tote le valores debe esser inter 0 e 100.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "escappar del bucla";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "continuar con le proxime iteration del bucla";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Escappar del bucla continente.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Saltar le resto de iste bucla e continuar con le proxime iteration.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Attention: Iste bloco pote solmente esser usate in un bucla.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "pro cata elemento %1 in lista %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Pro cata elemento in un lista, mitter lo in le variabile '%1' e exequer certe instructiones.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "contar con %1 de %2 a %3 per %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Mitter in le variabile \"%1\" le valores ab le numero initial usque al numero final, con passos secundo le intervallo specificate, e exequer le blocos specificate.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Adder un condition al bloco \"si\".";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Adder un condition final de reserva al bloco \"si\".";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Adde, remove o reordina sectiones pro reconfigurar iste bloco \"si\".";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "si non";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "si non si";
Blockly.Msg.CONTROLS_IF_MSG_IF = "si";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Si un valor es ver, exequer certe instructiones.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Si un valor es ver, exequer le prime bloco de instructiones. Si non, exequer le secunde bloco de instructiones.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Si le prime valor es ver, exequer le prime bloco de instructiones. Si non, si le secunde valor es ver, exequer le secunde bloco de instructiones.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Si le prime valor es ver, exequer le prime bloco de instructiones. Si non, si le secunde valor es ver, exequer le secunde bloco de instructiones. Si necun del valores es ver, exequer le ultime bloco de instructiones.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "face";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "repeter %1 vices";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Exequer certe instructiones plure vices.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "repeter usque a";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "repeter durante que";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Durante que un valor es false, exequer certe instructiones.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Durante que un valor es ver, exequer certe instructiones.";
Blockly.Msg.DELETE_ALL_BLOCKS = "Deler tote le %1 blocos?";
Blockly.Msg.DELETE_BLOCK = "Deler bloco";
Blockly.Msg.DELETE_X_BLOCKS = "Deler %1 blocos";
Blockly.Msg.DISABLE_BLOCK = "Disactivar bloco";
Blockly.Msg.DUPLICATE_BLOCK = "Duplicar";
Blockly.Msg.ENABLE_BLOCK = "Activar bloco";
Blockly.Msg.EXPAND_ALL = "Displicar blocos";
Blockly.Msg.EXPAND_BLOCK = "Displicar bloco";
Blockly.Msg.EXTERNAL_INPUTS = "Entrata externe";
Blockly.Msg.HELP = "Adjuta";
Blockly.Msg.INLINE_INPUTS = "Entrata interne";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "crear un lista vacue";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Retorna un lista, de longitude 0, sin datos.";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "lista";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Adde, remove o reordina sectiones pro reconfigurar iste bloco de listas.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "crear lista con";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Adder un elemento al lista.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Crear un lista con un numero qualcunque de elementos.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "prime";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "№ ab fin";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "prender";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "prender e remover";
Blockly.Msg.LISTS_GET_INDEX_LAST = "ultime";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "aleatori";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "remover";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Retorna le prime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Retorna le elemento presente al position specificate in un lista. № 1 es le ultime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Retorna le elemento presente al position specificate in un lista. № 1 es le prime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Retorna le ultime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Retorna un elemento aleatori in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Remove e retorna le prime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Remove e retorna le elemento presente al position specificate in un lista. № 1 es le ultime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Remove e retorna le elemento presente al position specificate in un lista. № 1 es le prime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Remove e retorna le ultime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Remove e retorna un elemento aleatori in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Remove le prime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Remove le elemento presente al position specificate in un lista. № 1 es le ultime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Remove le elemento presente al position specificate in un lista. № 1 es le prime elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Remove le ultime elemento in un lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Remove un elemento aleatori in un lista.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "usque al № ab fin";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "usque al №";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "usque al ultime";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "prender sublista ab initio";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "prender sublista ab le fin ab №";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "prender sublista ab №";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Crea un copia del parte specificate de un lista.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "cercar le prime occurrentia del elemento";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "cercar le ultime occurrentia del elemento";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Retorna le indice del prime/ultime occurrentia del elemento in le lista. Retorna 0 si le texto non es trovate.";
Blockly.Msg.LISTS_INLIST = "in lista";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 es vacue";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Retorna ver si le lista es vacue.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "longitude de %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Retorna le longitude de un lista.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "crear lista con elemento %1 repetite %2 vices";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Crea un lista que contine le valor fornite, repetite le numero specificate de vices.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "a";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "inserer in";
Blockly.Msg.LISTS_SET_INDEX_SET = "mitter";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Insere le elemento al initio de un lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Insere le elemento al position specificate in un lista. № 1 es le ultime elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Insere le elemento al position specificate in un lista. № 1 es le prime elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Adjunge le elemento al fin de un lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Insere le elemento a un position aleatori in un lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Defini le valor del prime elemento in un lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Defini le valor del elemento al position specificate in un lista. № 1 es le ultime elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Defini le valor del elemento al position specificate in un lista. № 1 es le prime elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Defini le valor del ultime elemento in un lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Defini le valor de un elemento aleatori in un lista.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "ascending";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "descending";  // untranslated
Blockly.Msg.LISTS_SORT_TITLE = "sort %1 %2 %3";  // untranslated
Blockly.Msg.LISTS_SORT_TOOLTIP = "Sort a copy of a list.";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabetic, ignore case";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "numeric";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "alphabetic";  // untranslated
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "Crear un lista per un texto";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "crear un texto per un lista";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "con delimitator";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "false";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Retorna o ver o false.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "ver";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Retornar ver si le duo entratas es equal.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Retornar ver si le prime entrata es major que le secunde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Retornar ver si le prime entrata es major que o equal al secunde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Retornar ver si le prime entrata es minor que le secunde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Retornar ver si le prime entrata es minor que o equal al secunde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Retornar ver si le duo entratas non es equal.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "non %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Retornar ver si le entrata es false. Retornar false si le entrata es ver.";
Blockly.Msg.LOGIC_NULL = "nulle";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Retorna nulle.";
Blockly.Msg.LOGIC_OPERATION_AND = "e";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "o";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Retornar ver si ambe entratas es ver.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Retornar ver si al minus un del entratas es ver.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "si false";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "si ver";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Verificar le condition in 'test'. Si le condition es ver, retorna le valor de 'si ver'; si non, retorna le valor de 'si false'.";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://ia.wikipedia.org/wiki/Arithmetica";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Retornar le summa del duo numeros.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Retornar le quotiente del duo numeros.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Retornar le differentia del duo numeros.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Retornar le producto del duo numeros.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Retornar le prime numero elevate al potentia del secunde numero.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";  // untranslated
Blockly.Msg.MATH_CHANGE_TITLE = "cambiar %1 per %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Adder un numero al variabile '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";  // untranslated
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Retornar un del constantes commun: π (3,141…), e (2,718…), φ (1,618…), sqrt(2) (1,414…), sqrt(½) (0,707…) o ∞ (infinite).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "limitar %1 inter %2 e %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Limitar un numero a esser inter le limites specificate (incluse).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "es divisibile per";
Blockly.Msg.MATH_IS_EVEN = "es par";
Blockly.Msg.MATH_IS_NEGATIVE = "es negative";
Blockly.Msg.MATH_IS_ODD = "es impare";
Blockly.Msg.MATH_IS_POSITIVE = "es positive";
Blockly.Msg.MATH_IS_PRIME = "es prime";
Blockly.Msg.MATH_IS_TOOLTIP = "Verificar si un numero es par, impare, prime, integre, positive, negative, o divisibile per un certe numero. Retorna ver o false.";
Blockly.Msg.MATH_IS_WHOLE = "es integre";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";  // untranslated
Blockly.Msg.MATH_MODULO_TITLE = "resto de %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Retornar le resto del division del duo numeros.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://ia.wikipedia.org/wiki/Numero";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Un numero.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "media del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "maximo del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "mediana del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "minimo del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modas del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "elemento aleatori del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "deviation standard del lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "summa del lista";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Retornar le media arithmetic del valores numeric in le lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Retornar le numero le plus grande in le lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Retornar le numero median del lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Retornar le numero le plus parve in le lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Retornar un lista del elemento(s) le plus commun in le lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Retornar un elemento aleatori del lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Retornar le deviation standard del lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Retornar le summa de tote le numeros in le lista.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "fraction aleatori";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Retornar un fraction aleatori inter 0.0 (incluse) e 1.0 (excluse).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_TITLE = "numero integre aleatori inter %1 e %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Retornar un numero integre aleatori inter le duo limites specificate, incluse.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://ia.wikipedia.org/wiki/Rotundamento";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "arrotundar";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "arrotundar a infra";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "arrotundar a supra";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Arrotundar un numero a supra o a infra.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://ia.wikipedia.org/wiki/Radice_quadrate";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolute";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "radice quadrate";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Retornar le valor absolute de un numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Retornar e elevate al potentia del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Retornar le logarithmo natural de un numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Retornar le logarithmo in base 10 del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Retornar le negation de un numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Retornar 10 elevate al potentia de un numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Retornar le radice quadrate de un numero.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";  // untranslated
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Retornar le arcocosino de un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Retornar le arcosino de un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Retornar le arcotangente de un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Retornar le cosino de un grado (non radiano).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Retornar le sino de un grado (non radiano).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Retornar le tangente de un grado (non radiano).";
Blockly.Msg.ME = "Io";
Blockly.Msg.NEW_VARIABLE = "Nove variabile...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nomine del nove variabile:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "permitter declarationes";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "con:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Executar le function '%1' definite per le usator.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Executar le function '%1' definite per le usator e usar su resultato.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "con:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Crear '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Describe this function...";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "facer qualcosa";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "pro";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Crea un function que non retorna un valor.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "retornar";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Crea un function que retorna un valor.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Attention: Iste function ha parametros duplicate.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Accentuar le definition del function";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Si un valor es ver, alora retornar un secunde valor.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Attention: Iste bloco pote solmente esser usate in le definition de un function.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "nomine del entrata:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Adder un entrata al function.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "entratas";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Adder, remover o reordinar le entratas pro iste function.";
Blockly.Msg.REDO = "Refacer";
Blockly.Msg.REMOVE_COMMENT = "Remover commento";
Blockly.Msg.RENAME_VARIABLE = "Renominar variabile...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Renominar tote le variabiles '%1' a:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "adjunger texto";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "a";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Adjunger un texto al variabile '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "in minusculas";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "con Initiales Majuscule";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "in MAJUSCULAS";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Retornar un copia del texto con differente majusculas/minusculas.";
Blockly.Msg.TEXT_CHARAT_FIRST = "prender le prime littera";
Blockly.Msg.TEXT_CHARAT_FROM_END = "prender ab le fin le littera №";
Blockly.Msg.TEXT_CHARAT_FROM_START = "prender le littera №";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "in le texto";
Blockly.Msg.TEXT_CHARAT_LAST = "prender le ultime littera";
Blockly.Msg.TEXT_CHARAT_RANDOM = "prender un littera aleatori";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Retorna le littera presente al position specificate.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Adder un elemento al texto.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "unir";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Adde, remove o reordina sectiones pro reconfigurar iste bloco de texto.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "ab le fin usque al littera №";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "usque al littera №";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "usque al ultime littera";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "in le texto";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "prender subcatena ab le prime littera";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "prender subcatena ab le fin ab le littera №";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "prender subcatena ab le littera №";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Retorna le parte specificate del texto.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "in le texto";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "cercar le prime occurrentia del texto";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "cercar le ultime occurrentia del texto";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Retorna le indice del prime/ultime occurrentia del prime texto in le secunde texto. Retorna 0 si le texto non es trovate.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 es vacue";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Retorna ver si le texto fornite es vacue.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "crear texto con";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Crear un pecia de texto uniente un certe numero de elementos.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "longitude de %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Retorna le numero de litteras (incluse spatios) in le texto fornite.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "scriber %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Scriber le texto, numero o altere valor specificate.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Peter un numero al usator.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Peter un texto al usator.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "peter un numero con le message";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "peter un texto con le message";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";  // untranslated
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Un littera, parola o linea de texto.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "remover spatios de ambe lateres de";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "remover spatios del sinistre latere de";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "remover spatios del dextre latere de";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Retornar un copia del texto con spatios eliminate de un extremitate o ambes.";
Blockly.Msg.TODAY = "Hodie";
Blockly.Msg.UNDO = "Disfacer";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "cosa";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Crea 'mitter %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Retorna le valor de iste variabile.";
Blockly.Msg.VARIABLES_SET = "mitter %1 a %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Crear 'prender %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Mitte iste variabile al valor del entrata.";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

Blockly.Msg.DOBOT_ON = "ON";
Blockly.Msg.DOBOT_OFF = "OFF";
Blockly.Msg.Dobot_Speed = "Speed";
Blockly.Msg.Dobot_DELTAPULSE = "DeltaPulse"
Blockly.Msg.DOBOT_ENABELD = "IsEnabled";
Blockly.Msg.DOBOT_GripperON = "Gripper";
Blockly.Msg.DOBOT_GripperOff = "Release";
Blockly.Msg.DOBOT_GripperPROHIBIT = "Disable";
Blockly.Msg.DOBOT_BASEIC_HOME = "Home";
Blockly.Msg.DOBOT_BASEIC_HOME_TOOLTIP = "Home";
Blockly.Msg.DOBOT_BASEIC_TIME = "GetTime";
Blockly.Msg.DOBOT_BASEIC_TIME_TOOLTIP = "GetTime, unit:s";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE = "ChooseEndTools";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_TOOLTIP = "Choose End Tools";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_SUCTIONCAP = "SuctionCup";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_GRIPPER = "Gripper";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_LASER = "Laser";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_PEN = "Pen";
Blockly.Msg.DOBOT_BASEIC_SETENDEFFECTORPARAMS = "Set End Effector Params"; //parekr add 2018 9 8
Blockly.Msg.DOBOT_BASEIC_SETENDEFFECTORPARAMS_TOOLTIP = "Set End Effector Params";
Blockly.Msg.DOBOT_SET_JUMP_HEIGHT = "SetJumpHeight";
Blockly.Msg.DOBOT_SET_JUMP_HEIGHT_TOOLTIP = "Set Jump Height";
Blockly.Msg.DOBOT_SETR = "SetR";
Blockly.Msg.DOBOT_SETR_TOOLTIP = "Set R";
Blockly.Msg.DOBOT_SUCTIONCAP = "SuctionCup";
Blockly.Msg.DOBOT_SUCTIONCAP_TOOLTIP = "SuctionCup";
Blockly.Msg.DOBOT_GRIPPER = "Gripper";
Blockly.Msg.DOBOT_GRIPPER_TOOLTIP = "Gripper";
Blockly.Msg.DOBOT_GET_CURRETN_COORDINATE= "GetCurrentCoordinate";
Blockly.Msg.DOBOT_GET_CURRETN_COORDINATE_TOOLTIP = "Get Current Coordinate";
Blockly.Msg.DOBOT_GET_CURRENT_ANGLE= "GetJointAngle";
Blockly.Msg.DOBOT_GET_CURRENT_ANGLE_TOOLTIP = "Get Joint Angle";
Blockly.Msg.DOBOT_DELAYTIME= "Delaytime";
Blockly.Msg.DOBOT_DELAYTIME_TOOLTIP = "Delaytime";
Blockly.Msg.DOBOT_MOTOR = "Motor"
Blockly.Msg.DOBOT_Value = "value";
Blockly.Msg.DOBOT_FREQUENCY = "frequency";
Blockly.Msg.DOBOT_DUTYCYCLE = "dutyCycle";

Blockly.Msg.DOBOT_joint1 = "Joint1";
Blockly.Msg.DOBOT_joint2 = "Joint2";
Blockly.Msg.DOBOT_joint3 = "Joint3";
Blockly.Msg.DOBOT_joint4 = "Joint4";
Blockly.Msg.DOBOT_covery = "L";
Blockly.Msg.DOBOT_xBias = "XBias";
Blockly.Msg.DOBOT_yBias = "YBias";
Blockly.Msg.DOBOT_zBias = "ZBias";
Blockly.Msg.DOBOT_j1 = "Joint1";
Blockly.Msg.DOBOT_j2 = "Joint2";
Blockly.Msg.DOBOT_j3 = "Joint3";
Blockly.Msg.DOBOT_j4 = "Joint4";
Blockly.Msg.DOBOT_j1Velocity = "Joint1Velocity";
Blockly.Msg.DOBOT_j2Velocity = "Joint2Velocity";
Blockly.Msg.DOBOT_j3Velocity = "Joint3Velocity";
Blockly.Msg.DOBOT_j4Velocity = "Joint4Velocity";
Blockly.Msg.DOBOT_j1Acceleration = "Joint1Acceleration";
Blockly.Msg.DOBOT_j2Acceleration = "Joint1Acceleration";
Blockly.Msg.DOBOT_j3Acceleration = "Joint1Accelerationy";
Blockly.Msg.DOBOT_j4Acceleration = "Joint1Acceleration";
Blockly.Msg.DOBOT_height = "Height";
Blockly.Msg.DOBOT_lVelocity = "lVelocity";
Blockly.Msg.DOBOT_lAcceleration = "lAcceleration";
Blockly.Msg.DOBOT_value = "Value";
Blockly.Msg.DOBOT_type = "Type";

Blockly.Msg.DOBOT_THRESHOLD = "Threshold";
Blockly.Msg.DOBOT_ANGLEUNIT = "Degree";
Blockly.Msg.DOBOT_SETLOSTSTEPPARAMS_TOOLTIP = "Set Lost Step Params";
Blockly.Msg.DOBOT_SETLOSTSTEPCMD_TOOLTIP = "Check Lost Step";
Blockly.Msg.Dobot_DISTANCE = "Distance";
Blockly.Msg.Dobot_IO_INPUT_3V = "Input 3.3V";
Blockly.Msg.Dobot_IO_INPUT_5V = "Input 5V";
Blockly.Msg.Dobot_IO_ADC = "Input AD";
Blockly.Msg.Dobot_IO_OUTPUT_3V = "Output 3.3V";
Blockly.Msg.Dobot_IO_OUTPUT_5V = "Output 5V";
Blockly.Msg.Dobot_IO_OUTPUT_12V = "Output 12V";
Blockly.Msg.Dobot_IO_PWM = "Output PWM";
Blockly.Msg.DOBOT_ACCELERATION = "Acceleration";
Blockly.Msg.DOBOT_VELOCITY = "Velocity";


//2017-07-03
Blockly.Msg.DOBOT_SET_JOINT_SPEED = "SetJointSpeed";
Blockly.Msg.DOBOT_SET_JOINT_SPEED_TOOLTIP = "Set Joint Speed";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED = "SetMotionRatio";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED_TOOLTIP = "Set Motion Ratio";
Blockly.Msg.DOBOT_VELOCITY_RATIO = "VelocityRatio";
Blockly.Msg.DOBOT_ACCELERATION_RATIO = "AccelerationRatio";
Blockly.Msg.DOBOT_SET_MOTOR = "SetMotorSpeed";
Blockly.Msg.DOBOT_SET_MOTOR_TOOLTIP = "Set Motor Speed";
Blockly.Msg.DOBOT_SET_MOTORS = "SetMotorSpeedAndDistance";
Blockly.Msg.DOBOT_SET_MOTORS_TOOLTIP = "Set Motor Speed And Distance";
Blockly.Msg.DOBOT_GOTO = "MoveTo";
Blockly.Msg.DOBOT_GOTO_TOOLTIP = "Move to";
Blockly.Msg.DOBOT_JUMPTO = "JumpTo";
Blockly.Msg.DOBOT_JUMPTO_TOOLTIP = "Jump To";
Blockly.Msg.DOBOT_MOVE = "MoveDistance";
Blockly.Msg.DOBOT_MOVE_TOOLTIP = "Move Distance";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE = "SetJointAngle";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE_TOOLTIP = "Set Joint Angle";
Blockly.Msg.DOBOT_SET_INFRARED_SENEOR = "SetPhotoelectricSensor";
Blockly.Msg.DOBOT_SET_INFRARED_SENEOR_TOOLTIP = "Set Photoelectric Sensor";
Blockly.Msg.DOBOT_GET_INFRARED_SENEOR = "GetPhotoelectricSensor";
Blockly.Msg.DOBOT_GET_INFRARED_SENEOR_TOOLTIP = "Detection of sensors in front of a certain distance whether there is an object, there are objects for 1; no object for 0.";
Blockly.Msg.DOBOT_SET_COLORSENEOR= "SetColorSensor";
Blockly.Msg.DOBOT_SET_COLORSENEOR_TOOLTIP = "Set Color Sensor";
Blockly.Msg.DOBOT_GET_COLORSENEOR= "IdentifyColor";
Blockly.Msg.DOBOT_GET_COLORSENEOR_TOOLTIP = "Used to identify 3 basic colors: blue, green, and red. Returns 1 when detecting the color, or else returns 0.";
Blockly.Msg.DOBOT_SET_CONVEYOR = "SetConveyor"
Blockly.Msg.DOBOT_SET_CONVEYOR_TOOLTIP = "Set Conveyor"
Blockly.Msg.DOBOT_SET_LINEAR_RAIL = "SetLinearRail"
Blockly.Msg.DOBOT_SET_LINEAR_RAIL_TOOLTIP = "Set Linear Rail"
Blockly.Msg.DOBOT_SETL = "MoveLinearRailTo";
Blockly.Msg.DOBOT_SETL_TOOLTIP = "Move Linear Rail To";
Blockly.Msg.DOBOT_SET_L_SPEED = "SetLinearRailSpeed";
Blockly.Msg.DOBOT_SET_L_SPEED_TOOLTIP = "Set Linear Rail Speed";
Blockly.Msg.DOBOT_POWER = "Power";
Blockly.Msg.DOBOT_LASER = "Laser";
Blockly.Msg.DOBOT_LASER_TOOLTIP = "Laser";
Blockly.Msg.DOBOT_SET_OUTPUT12V = "Set12VOutput  ";
Blockly.Msg.DOBOT_SET_OUTPUT12V_TOOLTIP = "Set 12V Output";
Blockly.Msg.DOBOT_SET_OUTPUT= "SetLevelOutput  ";
Blockly.Msg.DOBOT_SET_OUTPUT_TOOLTIP = "Set Level Output";
Blockly.Msg.DOBOT_GET_INPUT_EIO= "GetLevelInput  ";
Blockly.Msg.DOBOT_GET_INPUT_EIO_TOOLTIP = "Get Level Input";
Blockly.Msg.DOBOT_SET_PWM = "SetPWMOutput  ";
Blockly.Msg.DOBOT_SET_PWM_TOOLTIP = "Set PWM Output";
Blockly.Msg.DOBOT_GET_PWM = "GetPWMInput  ";
Blockly.Msg.DOBOT_GET_PWM_TOOLTIP = "Get PWM Input";
Blockly.Msg.DOBOT_GET_ADC = "GetADInput  ";
Blockly.Msg.DOBOT_GET_ADC_TOOLTIP = "Get AD Input";
Blockly.Msg.DOBOT_SET_IOMULTIPLEXING= "SetIOMultiplexing";
Blockly.Msg.DOBOT_SET_IOMULTIPLEXING_TOOLTIP = "SetIOMultiplexing";

//2017-09-27
Blockly.Msg.DOBOT_SET_COORDINATE_SPEED = "SetCoordinateSpeed";
Blockly.Msg.DOBOT_SET_COORDINATE_SPEED_TOOLTIP = "Set Coordinate Speed";

//2018-04-21
Blockly.Msg.DOBOT_SET_OUTPUT5V = "Set5VOutput  ";
Blockly.Msg.DOBOT_SET_OUTPUT5V_TOOLTIP = "Set 5V Output";

//2018-06-06
Blockly.Msg.DOBOT_PORT = "Port";
Blockly.Msg.DOBOT_HARDWARE = "Hardware";
Blockly.Msg.DOBOT_NEW = "V2";
Blockly.Msg.DOBOT_OLD = "V1";
Blockly.Msg.DOBOT_VERSION = "Version";


//2019-04-25
Blockly.Msg.DOBOT_MagicianLite = "Magician Lite";
Blockly.Msg.DOBOT_Controller = "Magic Box";
Blockly.Msg.DOBOT_DevType = "DevType";

Blockly.Msg.DOBOT_Set_SeeedRgbLED = "SetSeeedRgbLED";
Blockly.Msg.DOBOT_Set_SeeedRgbLED_TOOLTIP = "SetSeeedRgbLED";
Blockly.Msg.DOBOT_Get_SeeedColorSensor = "GetSeeedColorSensor";
Blockly.Msg.DOBOT_Get_SeeedColorSensor_TOOLTIP = "GetSeeedColorSensor";
Blockly.Msg.DOBOT_Set_SeeedColorSensor = "SetSeeedColorSensor";
Blockly.Msg.DOBOT_Set_SeeedColorSensor_TOOLTIP = "SetSeeedColorSensor";
Blockly.Msg.DOBOT_Get_SeeedInfraredSensor = "GetSeeedInfraredSensor";
Blockly.Msg.DOBOT_Get_SeeedInfraredSensor_TOOLTIP = "GetSeeedInfraredSensor";
Blockly.Msg.DOBOT_Set_SeeedInfraredSensor = "SetSeeedInfraredSensor";
Blockly.Msg.DOBOT_Set_SeeedInfraredSensor_TOOLTIP = "SetSeeedInfraredSensor";
Blockly.Msg.DOBOT_Get_SeeedTemperatureSensor = "GetSeeedTemperatureSensor";
Blockly.Msg.DOBOT_Get_SeeedTemperatureSensor_TOOLTIP = "GetSeeedTemperatureSensor";
Blockly.Msg.DOBOT_Set_SeeedTemperatureSensor = "SetSeeedTemperatureSensor";
Blockly.Msg.DOBOT_Set_SeeedTemperatureSensor_TOOLTIP = "SetSeeedTemperatureSensor";
Blockly.Msg.DOBOT_Get_SeeedDistanceSensor = "GetSeeedDistanceSensor";
Blockly.Msg.DOBOT_Get_SeeedDistanceSensor_TOOLTIP = "GetSeeedDistanceSensor";

//2019-11-06
Blockly.Msg.DOBOT_GET_ENDEFFECTORTYPE = "GetEndEffectorType";
Blockly.Msg.DOBOT_GET_ENDEFFECTORTYPE_TOOLTIP = "GetEndEffectorType";
Blockly.Msg.DOBOT_SET_SERVOANGLE = "SetServoAngle";
Blockly.Msg.DOBOT_SET_SERVOANGLE_TOOLTIP = "SetServoAngle";
Blockly.Msg.DOBOT_SERVO_PORT = "Servo";
Blockly.Msg.DOBOT_SERVO_ANGLE_VALUE = "Angle value";
Blockly.Msg.DOBOT_GET_SERVOANGLE = "GetServoAngle";
Blockly.Msg.DOBOT_GET_SERVOANGLE_TOOLTIP = "GetServoAngle";
// Blockly.Msg.DOBOT_SERVO_ANGLE = "度";
Blockly.Msg.DOBOT_SET_ARM_SPEED_RATIO = "SetArmSpeedRatio";
Blockly.Msg.DOBOT_SET_ARM_SPEED_RATIO_TOOLTIP = "SetArmSpeedRatio";
Blockly.Msg.DOBOT_SET_ARM_SPEED_MODE = "Run Mode";
Blockly.Msg.DOBOT_SET_ARM_SPEED_MODE_JOG = "JOG";
Blockly.Msg.DOBOT_SET_ARM_SPEED_MODE_OTHER = "OTHER";
Blockly.Msg.DOBOT_GET_ARM_SPEED_RATIO = "GetArmSpeedRatio";
Blockly.Msg.DOBOT_GET_ARM_SPEED_RATIO_TOOLTIP = "GetArmSpeedRatio";
Blockly.Msg.DOBOT_SET_Liner_SPEED_RATIO = "SetLSpeedRatio";
Blockly.Msg.DOBOT_SET_Liner_SPEED_RATIO_TOOLTIP = "SetLSpeedRatio";
Blockly.Msg.DOBOT_GET_Liner_SPEED_RATIO = "GetLSpeedRatio";
Blockly.Msg.DOBOT_GET_Liner_SPEED_RATIO_TOOLTIP = "GetLSpeedRatio";
Blockly.Msg.DOBOT_SET_LinearRail_SPEED_MODE = "Run Mode";
Blockly.Msg.DOBOT_SET_LinearRail_SPEED_MODE_JOG = "JOG";
Blockly.Msg.DOBOT_SET_LinearRail_SPEED_MODE_PTP = "PTP";
Blockly.Msg.DOBOT_SET_PROGBAR = "SetProgbar";
Blockly.Msg.DOBOT_SET_PROGBAR_VALUE = "Progress value";
Blockly.Msg.DOBOT_SET_PROGBAR_TOOLTIP = "SetProgbar";
Blockly.Msg.DOBOT_SET_PRINTINFO = "PrintInfo";
Blockly.Msg.DOBOT_SET_PRINTINFO_VALUE = "Infomation";
Blockly.Msg.DOBOT_SET_PRINTINFO_TOOLTIP = "PrintInfo";
Blockly.Msg.ADDPOINT = "AddPoint";